Repository team-staccato/staccato-ios, pull requests merged in 2025-03, with the labels that each got.

#43 [Feat/#30] 네트워크 레이어 보완, 카테고리 리스트 API 연결, 정렬/필터 팝업 UI 구현
  Staccato-iOS/Staccato-iOS.xcodeproj/project.pbxproj
  Staccato-iOS/Staccato-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Staccato-iOS/Staccato-iOS/Model/Category/CategoryListFilterType.swift
  Staccato-iOS/Staccato-iOS/Model/Category/CategoryListSortType.swift
  Staccato-iOS/Staccato-iOS/Model/Category/CategoryModel.swift
  Staccato-iOS/Staccato-iOS/Model/Staccato/CommentModel.swift
  Staccato-iOS/Staccato-iOS/Model/Staccato/FeelingType.swift
  Staccato-iOS/Staccato-iOS/Model/Staccato/StaccatoDetailModel.swift
  Staccato-iOS/Staccato-iOS/Presentation/View/CategoryList/CategoryListCell.swift
  Staccato-iOS/Staccato-iOS/Presentation/View/CategoryList/CategoryListSortFilterView.swift
  Staccato-iOS/Staccato-iOS/Presentation/View/CategoryList/CategoryListView.swift
  Staccato-iOS/Staccato-iOS/Presentation/ViewModel/CategoryList/CategoryListViewModel.swift
  Staccato-iOS/Staccato-iOS/Service/Category/CategoryEndpoint.swift
  Staccato-iOS/Staccato-iOS/Service/Category/CategoryService.swift
  Staccato-iOS/Staccato-iOS/Service/Category/DTO/GetCategoryListRequestQuery.swift
  Staccato-iOS/Staccato-iOS/Service/Category/DTO/GetCategoryListResponse.swift
  Staccato-iOS/Staccato-iOS/Util/Network/APIs/AuthorizationAPI.swift
  Staccato-iOS/Staccato-iOS/Util/Network/HeaderType.swift
  Staccato-iOS/Staccato-iOS/Util/Network/NetworkService.swift
  Staccato-iOS/Staccato-iOS/Util/Network/STService.swift
  Staccato-iOS/Staccato-iOS/Util/Theme/StaccatoIcon.swift
Labels: feat, network, 🥑 유림

#41 [Feat/#40] 홈화면 네비게이션 리팩토링, 지도 내위치 버튼 커스텀, 스타카토 생성 버튼 구현
  Staccato-iOS/Staccato-iOS.xcodeproj/project.pbxproj
  Staccato-iOS/Staccato-iOS/App/Staccato_iOSApp.swift
  Staccato-iOS/Staccato-iOS/Presentation/View/CategoryList/CategoryListSortFilterView.swift
  Staccato-iOS/Staccato-iOS/Presentation/View/CategoryList/CategoryListView.swift
  Staccato-iOS/Staccato-iOS/Presentation/View/Home/GMSMapViewRepresentable.swift
  Staccato-iOS/Staccato-iOS/Presentation/View/Home/HomeView.swift
  Staccato-iOS/Staccato-iOS/Util/NavigationState/NavigationState.swift
  Staccato-iOS/Staccato-iOS/Util/Theme/StaccatoIcon.swift
Labels: feat, 🥑 유림

#42 [Feat/#38] StaccatoDetail 이미지 캐러셀 커스텀 (+네비게이션 백버튼 색 변경)
  Staccato-iOS/Staccato-iOS/Presentation/Components/ImageSliderWithDot.swift
  Staccato-iOS/Staccato-iOS/Presentation/Components/StaccatoNavigationBar.swift
  Staccato-iOS/Staccato-iOS/Presentation/View/StaccatoDetail/StaccatoDetailView.swift
Labels: feat, 🥑 유림

#46 Feat/#22 네트워크 에러 핸들링, 유효성 조건 변경
  Staccato-iOS/Staccato-iOS/Presentation/View/SignIn/SignInView.swift
  Staccato-iOS/Staccato-iOS/Presentation/ViewModel/SignIn/SignInViewModel.swift
  Staccato-iOS/Staccato-iOS/Util/Network/NetworkError.swift
  Staccato-iOS/Staccato-iOS/Util/Network/NetworkService.swift
Labels: feat

#51 [Hotfix/#50] modalNavigationState 변수명 잘못 입력되어 발생한 컴파일 에러 수정
  Staccato-iOS/Staccato-iOS/Presentation/View/Home/GMSMapViewRepresentable.swift
  Staccato-iOS/Staccato-iOS/Presentation/View/Home/HomeView.swift
  Staccato-iOS/Staccato-iOS/Util/Network/NetworkService.swift
Labels: hotfix, 🥑 유림

#49 [Refactor/#48] Network 관련 메서드 Swift Concurrency 처리
  Staccato-iOS/Staccato-iOS.xcodeproj/project.pbxproj
  Staccato-iOS/Staccato-iOS/Presentation/View/CategoryList/CategoryListView.swift
  Staccato-iOS/Staccato-iOS/Presentation/View/Home/HomeView.swift
  Staccato-iOS/Staccato-iOS/Presentation/View/SignIn/SignInView.swift
  Staccato-iOS/Staccato-iOS/Presentation/ViewModel/CategoryList/CategoryListViewModel.swift
  Staccato-iOS/Staccato-iOS/Presentation/ViewModel/Home/HomeViewModel.swift
  Staccato-iOS/Staccato-iOS/Presentation/ViewModel/SignIn/SignInViewModel.swift
  Staccato-iOS/Staccato-iOS/Service/Category/CategoryService.swift
  Staccato-iOS/Staccato-iOS/Service/Staccato/StaccatoService.swift
  Staccato-iOS/Staccato-iOS/Util/Network/NetworkError.swift
  Staccato-iOS/Staccato-iOS/Util/Network/NetworkService.swift
  Staccato-iOS/Staccato-iOS/Util/StaccatoError.swift
Labels: refactor

#57 [Feat/#52] 기분 선택 API 연결 (+ response 없는 Service 구현)
  Staccato-iOS/Staccato-iOS/Model/Staccato/FeelingType.swift
  Staccato-iOS/Staccato-iOS/Model/Staccato/StaccatoDetailModel.swift
  Staccato-iOS/Staccato-iOS/Presentation/View/StaccatoDetail/StaccatoDetailView.swift
  Staccato-iOS/Staccato-iOS/Presentation/ViewModel/Home/HomeViewModel.swift
  Staccato-iOS/Staccato-iOS/Service/Staccato/DTO/PostStaccatoFeelingRequest.swift
  Staccato-iOS/Staccato-iOS/Service/Staccato/StaccatoEndpoint.swift
  Staccato-iOS/Staccato-iOS/Service/Staccato/StaccatoService.swift
  Staccato-iOS/Staccato-iOS/Util/Extension/Ex+Encodable.swift
  Staccato-iOS/Staccato-iOS/Util/Network/NetworkService.swift
Labels: network, 🥑 유림

#58 [Feat/#53] 댓글 CRUD API 연결 (뷰 연결 X)
  Staccato-iOS/Staccato-iOS/Service/Comment/CommentEndpoint.swift
  Staccato-iOS/Staccato-iOS/Service/Comment/CommentService.swift
  Staccato-iOS/Staccato-iOS/Service/Comment/DTO/GetCommentsResponse.swift
  Staccato-iOS/Staccato-iOS/Service/Comment/DTO/PostCommentRequest.swift
  Staccato-iOS/Staccato-iOS/Service/Comment/DTO/PutCommentRequest.swift
  Staccato-iOS/Staccato-iOS/Util/Model/Comment/Comment.swift
  Staccato-iOS/Staccato-iOS/Util/Model/Comment/CommentRequest.swift
  Staccato-iOS/Staccato-iOS/Util/Model/Comment/CommentResponse.swift
  Staccato-iOS/Staccato-iOS/Util/Model/Comment/CommentUpdateRequest.swift
  Staccato-iOS/Staccato-iOS/Util/Network/NetworkService.swift
  Staccato-iOS/Staccato-iOS/Util/Network/STService.swift
Labels: network, 🥑 유림

#56 [Feat/#55] 마이페이지 프로필 조회 API 연결, 코드 클립보드 복사 기능 추가
  Staccato-iOS/Staccato-iOS/App/Staccato_iOSApp.swift
  Staccato-iOS/Staccato-iOS/Model/Profile/ProfileModel.swift
  Staccato-iOS/Staccato-iOS/Presentation/View/MyPage/MyPageView.swift
  Staccato-iOS/Staccato-iOS/Presentation/ViewModel/MyPage/MyPageViewModel.swift
  Staccato-iOS/Staccato-iOS/Service/MyPage/DTO/GetProfileResponse.swift
  Staccato-iOS/Staccato-iOS/Service/MyPage/MyPageEndPoint.swift
  Staccato-iOS/Staccato-iOS/Service/MyPage/MyPageService.swift
  Staccato-iOS/Staccato-iOS/Util/Network/STService.swift
Labels: feat
