Repository team-staccato/staccato-ios, pull requests merged in 2025-07, with the labels that each got.

#188 [Setting/#186] Crashlytics 적용
  Staccato-iOS/Staccato-iOS.xcodeproj/project.pbxproj
Labels: ⚙️ Settings

#187 [Feat/#172] 지도 클러스터링 구현
  Staccato-iOS/Staccato-iOS.xcodeproj/project.pbxproj
  Staccato-iOS/Staccato-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Staccato-iOS/Staccato-iOS/Model/Staccato/StaccatoCoordinateModel.swift
  Staccato-iOS/Staccato-iOS/Presentation/Category/View/Cell/CategoryListCell.swift
  Staccato-iOS/Staccato-iOS/Presentation/Common/Component/StaccatoNavigationBar.swift
  Staccato-iOS/Staccato-iOS/Presentation/Home/View/Cell/StaccatoListCell.swift
  Staccato-iOS/Staccato-iOS/Presentation/Home/View/Component/GMUClusterItemWrapper.swift
  Staccato-iOS/Staccato-iOS/Presentation/Home/View/Component/StaccatoClusterIconGenerator.swift
  Staccato-iOS/Staccato-iOS/Presentation/Home/View/GMSMapViewRepresentable.swift
  Staccato-iOS/Staccato-iOS/Presentation/Home/View/HomeView.swift
  Staccato-iOS/Staccato-iOS/Presentation/Home/View/StaccatoListView.swift
  Staccato-iOS/Staccato-iOS/Presentation/Home/ViewModel/HomeViewModel.swift
  Staccato-iOS/Staccato-iOS/Resources/Assets.xcassets/Icons/ic_marker.imageset/Contents.json
  Staccato-iOS/Staccato-iOS/Resources/Assets.xcassets/Icons/ic_marker.imageset/ic_marker.svg
  Staccato-iOS/Staccato-iOS/Resources/Assets.xcassets/Image/clusters/Contents.json
  Staccato-iOS/Staccato-iOS/Resources/Assets.xcassets/Image/clusters/img_cluster_blue.imageset/Contents.json
  Staccato-iOS/Staccato-iOS/Resources/Assets.xcassets/Image/clusters/img_cluster_blue.imageset/img_cluster_blue.png
  Staccato-iOS/Staccato-iOS/Resources/Assets.xcassets/Image/clusters/img_cluster_blue.imageset/img_cluster_blue@2x.png
  Staccato-iOS/Staccato-iOS/Resources/Assets.xcassets/Image/clusters/img_cluster_blue.imageset/img_cluster_blue@3x.png
  Staccato-iOS/Staccato-iOS/Resources/Assets.xcassets/Image/clusters/img_cluster_mint.imageset/Contents.json
  Staccato-iOS/Staccato-iOS/Resources/Assets.xcassets/Image/clusters/img_cluster_mint.imageset/img_cluster_mint.png
  Staccato-iOS/Staccato-iOS/Resources/Assets.xcassets/Image/clusters/img_cluster_mint.imageset/img_cluster_mint@2x.png
  Staccato-iOS/Staccato-iOS/Resources/Assets.xcassets/Image/clusters/img_cluster_mint.imageset/img_cluster_mint@3x.png
  Staccato-iOS/Staccato-iOS/Resources/Assets.xcassets/Image/clusters/img_cluster_purple.imageset/Contents.json
  Staccato-iOS/Staccato-iOS/Resources/Assets.xcassets/Image/clusters/img_cluster_purple.imageset/img_cluster_purple.png
  Staccato-iOS/Staccato-iOS/Resources/Assets.xcassets/Image/clusters/img_cluster_purple.imageset/img_cluster_purple@2x.png
  Staccato-iOS/Staccato-iOS/Resources/Assets.xcassets/Image/clusters/img_cluster_purple.imageset/img_cluster_purple@3x.png
  Staccato-iOS/Staccato-iOS/Service/Staccato/DTO/GetStaccatoListResponse.swift
Labels: ✨ Feat

#191 [Chore/#185] 2.1.0 release
  Staccato-iOS/Staccato-iOS.xcodeproj/project.pbxproj
Labels: ✏️ Chore, 🚀 release

#201 [Fix/#193] Push 알림 서버 token deviceid 수정
  Staccato-iOS/Staccato-iOS/App/AppDelegate.swift
Labels: 🛠️ Fix

#202 [Feat/#192] Push 알림 화면 이동 구현
  Staccato-iOS/Staccato-iOS/App/AppDelegate.swift
  Staccato-iOS/Staccato-iOS/Model/PushNotification/PushNotificationType.swift
  Staccato-iOS/Staccato-iOS/Presentation/Category/View/CategoryDetailView.swift
  Staccato-iOS/Staccato-iOS/Presentation/Category/View/CategoryEditorView.swift
  Staccato-iOS/Staccato-iOS/Presentation/Home/View/GMSMapViewRepresentable.swift
  Staccato-iOS/Staccato-iOS/Presentation/Home/View/HomeView.swift
  Staccato-iOS/Staccato-iOS/Presentation/MyPage/View/CategoryInvitationManagerView.swift
  Staccato-iOS/Staccato-iOS/Presentation/MyPage/View/MyPageView.swift
  Staccato-iOS/Staccato-iOS/Presentation/SignIn/ViewModel/SignInViewModel.swift
  Staccato-iOS/Staccato-iOS/Presentation/Staccato/View/StaccatoDetailView.swift
  Staccato-iOS/Staccato-iOS/Presentation/Staccato/View/StaccatoEditorView.swift
  Staccato-iOS/Staccato-iOS/Util/Extension/Ex+Notification.swift
  Staccato-iOS/Staccato-iOS/Util/Manager/BottomSheetDetentManager.swift
  Staccato-iOS/Staccato-iOS/Util/Manager/PushNotificationManager.swift
Labels: ✨ Feat
