Repository team-staccato/staccato-ios, pull requests merged in 2025-05, with the labels that each got.

#90 [Feat/#74] 카테고리 수정 기능 구현
  Staccato-iOS/Staccato-iOS/Presentation/View/Category/CategoryDetailView.swift
  Staccato-iOS/Staccato-iOS/Presentation/View/Category/CategoryEditorView.swift
  Staccato-iOS/Staccato-iOS/Presentation/View/Category/CategoryListView.swift
  Staccato-iOS/Staccato-iOS/Presentation/View/Home/HomeView.swift
  Staccato-iOS/Staccato-iOS/Presentation/View/Staccato/StaccatoEditorView.swift
  Staccato-iOS/Staccato-iOS/Presentation/ViewModel/CategoryEditor/CategoryEditorViewModel.swift
  Staccato-iOS/Staccato-iOS/Service/Category/CategoryEndpoint.swift
  Staccato-iOS/Staccato-iOS/Service/Category/CategoryService.swift
  Staccato-iOS/Staccato-iOS/Service/Category/DTO/ModifyCategoryRequestQuery.swift
Labels: feat

#87 [Feat/#34] 스타카토 생성 기능 구현
  Staccato-iOS/Staccato-iOS/Model/Category/CategoryDetailModel.swift
  Staccato-iOS/Staccato-iOS/Model/Staccato/UploadablePhoto.swift
  Staccato-iOS/Staccato-iOS/Presentation/View/Category/CategoryDetailView.swift
  Staccato-iOS/Staccato-iOS/Presentation/View/Category/CategoryEditorView.swift
  Staccato-iOS/Staccato-iOS/Presentation/View/Category/CategoryListView.swift
  Staccato-iOS/Staccato-iOS/Presentation/View/Home/HomeView.swift
  Staccato-iOS/Staccato-iOS/Presentation/View/Staccato/DatePickerView.swift
  Staccato-iOS/Staccato-iOS/Presentation/View/Staccato/StaccatoEditorView.swift
  Staccato-iOS/Staccato-iOS/Presentation/View/StaccatoDetail/StaccatoDetailView.swift
  Staccato-iOS/Staccato-iOS/Presentation/ViewModel/CategoryEditor/CategoryEditorViewModel.swift
  Staccato-iOS/Staccato-iOS/Presentation/ViewModel/Staccato/StaccatoEditorViewModel.swift
  Staccato-iOS/Staccato-iOS/Service/Category/CategoryEndpoint.swift
  Staccato-iOS/Staccato-iOS/Service/Category/CategoryService.swift
  Staccato-iOS/Staccato-iOS/Service/Category/DTO/ModifyCategoryRequestQuery.swift
  Staccato-iOS/Staccato-iOS/Service/Staccato/DTO/CreateStaccatoRequest.swift
  Staccato-iOS/Staccato-iOS/Service/Staccato/DTO/ModifyStaccatoRequest.swift
  Staccato-iOS/Staccato-iOS/Service/Staccato/StaccatoEndpoint.swift
  Staccato-iOS/Staccato-iOS/Service/Staccato/StaccatoService.swift
  Staccato-iOS/Staccato-iOS/Util/Extension/Ex+Date.swift
  Staccato-iOS/Staccato-iOS/Util/NavigationState/NavigationState.swift
Labels: feat

#91 Feat/#89 스타카토 삭제 기능
  Staccato-iOS/Staccato-iOS/App/Staccato_iOSApp.swift
  Staccato-iOS/Staccato-iOS/Presentation/View/Home/GMSMapViewRepresentable.swift
  Staccato-iOS/Staccato-iOS/Presentation/View/Home/HomeView.swift
  Staccato-iOS/Staccato-iOS/Presentation/View/StaccatoDetail/StaccatoDetailView.swift
  Staccato-iOS/Staccato-iOS/Presentation/ViewModel/StaccatoDetail/StaccatoDetailViewModel.swift
  Staccato-iOS/Staccato-iOS/Service/Staccato/StaccatoEndpoint.swift
  Staccato-iOS/Staccato-iOS/Service/Staccato/StaccatoService.swift
Labels: feat, 🥑 유림

#93 [Release/#92] 1차 QA 준비
  Staccato-iOS/Staccato-iOS.xcodeproj/project.pbxproj
  Staccato-iOS/Staccato-iOS.xcodeproj/xcshareddata/xcschemes/Staccato-iOS.xcscheme
  Staccato-iOS/Staccato-iOS/App/Staccato_iOSApp.swift
  Staccato-iOS/Staccato-iOS/Model/Error/ErrorResponse.swift
  Staccato-iOS/Staccato-iOS/Model/Staccato/StaccatoDetailModel.swift
  Staccato-iOS/Staccato-iOS/Presentation/View/Category/CategoryDetailView.swift
  Staccato-iOS/Staccato-iOS/Presentation/View/Category/CategoryEditorView.swift
  Staccato-iOS/Staccato-iOS/Presentation/View/Category/CategoryListView.swift
  Staccato-iOS/Staccato-iOS/Presentation/View/Home/GMSMapViewRepresentable.swift
  Staccato-iOS/Staccato-iOS/Presentation/View/Home/HomeView.swift
  Staccato-iOS/Staccato-iOS/Presentation/View/MyPage/MyPageView.swift
  Staccato-iOS/Staccato-iOS/Presentation/View/SignIn/RecoverAccountView.swift
  Staccato-iOS/Staccato-iOS/Presentation/View/SignIn/SignInView.swift
  Staccato-iOS/Staccato-iOS/Presentation/View/Staccato/DatePickerView.swift
  Staccato-iOS/Staccato-iOS/Presentation/View/Staccato/StaccatoDetailView.swift
  Staccato-iOS/Staccato-iOS/Presentation/View/Staccato/StaccatoEditorView.swift
  Staccato-iOS/Staccato-iOS/Presentation/ViewModel/Category/CategoryEditorViewModel.swift
  Staccato-iOS/Staccato-iOS/Presentation/ViewModel/Category/CategoryViewModel.swift
  Staccato-iOS/Staccato-iOS/Presentation/ViewModel/CategoryList/CategoryDetailViewModel.swift
  Staccato-iOS/Staccato-iOS/Presentation/ViewModel/Home/HomeViewModel.swift
  Staccato-iOS/Staccato-iOS/Presentation/ViewModel/SignIn/RecoverAccountViewModel.swift
  Staccato-iOS/Staccato-iOS/Presentation/ViewModel/SignIn/SignInViewModel.swift
  Staccato-iOS/Staccato-iOS/Presentation/ViewModel/Staccato/StaccatoDetailViewModel.swift
  Staccato-iOS/Staccato-iOS/Presentation/ViewModel/Staccato/StaccatoEditorViewModel.swift
  Staccato-iOS/Staccato-iOS/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  Staccato-iOS/Staccato-iOS/Resources/Assets.xcassets/AppIcon.appiconset/staccato-icon.png
  Staccato-iOS/Staccato-iOS/Resources/Assets.xcassets/Color/Text/gray1.colorset/Contents.json
  Staccato-iOS/Staccato-iOS/Resources/Assets.xcassets/Color/Text/gray2.colorset/Contents.json
  Staccato-iOS/Staccato-iOS/Service/Comment/CommentEndpoint.swift
  Staccato-iOS/Staccato-iOS/Service/Staccato/DTO/CreateStaccatoRequest.swift
  Staccato-iOS/Staccato-iOS/Service/Staccato/DTO/PostShareLinkResponse.swift
  Staccato-iOS/Staccato-iOS/Service/Staccato/StaccatoEndpoint.swift
  Staccato-iOS/Staccato-iOS/Service/Staccato/StaccatoService.swift
  Staccato-iOS/Staccato-iOS/Support/Config/Debug.xcconfig
  Staccato-iOS/Staccato-iOS/Support/Config/Release.xcconfig
  Staccato-iOS/Staccato-iOS/Support/Info.plist
  Staccato-iOS/Staccato-iOS/Util/Extension/Ex+Date.swift
  Staccato-iOS/Staccato-iOS/Util/Manager/AppVersionCheckManager.swift
  Staccato-iOS/Staccato-iOS/Util/Theme/StaccatoIcon.swift
Labels: feat, fix, 🥑 유림

#100 [Fix/#99] QA 대응
  Staccato-iOS/Staccato-iOS.xcodeproj/project.pbxproj
  Staccato-iOS/Staccato-iOS/Presentation/Components/StaccatoDatePicker/StaccatoDatePicker+Calendar.swift
  Staccato-iOS/Staccato-iOS/Presentation/Components/StaccatoDatePicker/StaccatoDatePicker.swift
  Staccato-iOS/Staccato-iOS/Presentation/View/Category/CategoryEditorView.swift
  Staccato-iOS/Staccato-iOS/Presentation/View/Staccato/StaccatoDetailView.swift
  Staccato-iOS/Staccato-iOS/Presentation/View/Staccato/StaccatoEditorView.swift
  Staccato-iOS/Staccato-iOS/Presentation/ViewModel/Staccato/StaccatoEditorViewModel.swift
  Staccato-iOS/Staccato-iOS/Service/Staccato/DTO/ModifyStaccatoRequest.swift
  Staccato-iOS/Staccato-iOS/Support/LaunchScreen.storyboard
  Staccato-iOS/Staccato-iOS/Util/Network/NetworkError.swift
Labels: fix

#102 [Fix/#101] 줄리 QA 대응
  Staccato-iOS/Staccato-iOS/App/Staccato_iOSApp.swift
  Staccato-iOS/Staccato-iOS/Presentation/Components/StaccatoNavigationBar.swift
  Staccato-iOS/Staccato-iOS/Presentation/View/Category/CategoryDetailView.swift
  Staccato-iOS/Staccato-iOS/Presentation/View/Category/StaccatoCollectionCell.swift
  Staccato-iOS/Staccato-iOS/Presentation/View/Home/GMSMapViewRepresentable.swift
  Staccato-iOS/Staccato-iOS/Presentation/View/Home/HomeView.swift
  Staccato-iOS/Staccato-iOS/Presentation/View/Staccato/PlaceSearchView.swift
  Staccato-iOS/Staccato-iOS/Presentation/View/Staccato/StaccatoDetailView.swift
  Staccato-iOS/Staccato-iOS/Presentation/View/Staccato/StaccatoEditorView.swift
  Staccato-iOS/Staccato-iOS/Presentation/ViewModel/Home/HomeViewModel.swift
  Staccato-iOS/Staccato-iOS/Presentation/ViewModel/Staccato/StaccatoEditorViewModel.swift
  Staccato-iOS/Staccato-iOS/Util/Extension/Ex+ButtonStyle.swift
  Staccato-iOS/Staccato-iOS/Util/Manager/AppVersionCheckManager.swift
  Staccato-iOS/Staccato-iOS/Util/Manager/HomeModalManager.swift
  Staccato-iOS/Staccato-iOS/Util/Manager/STLocationManager.swift
  Staccato-iOS/Staccato-iOS/Util/Manager/StaccatoAlertManager.swift
  Staccato-iOS/Staccato-iOS/Util/Size/HomeModalSize.swift
  Staccato-iOS/Staccato-iOS/Util/Size/ScreenUtils.swift
Labels: fix, 🥑 Julie

#106 [Chore/#105] Dev-only 로그아웃 버튼 구현
  Staccato-iOS/Staccato-iOS/Presentation/View/MyPage/MyPageView.swift
  Staccato-iOS/Staccato-iOS/Presentation/ViewModel/SignIn/SignInViewModel.swift
Labels: 🥑 Julie, chore

#118 [Fix/#117] 스타카토 상세 - Comment UI QA 반영
  .gitignore
  Staccato-iOS/Staccato-iOS/Presentation/Components/StaccatoTextField.swift
  Staccato-iOS/Staccato-iOS/Presentation/View/Staccato/StaccatoDetailView.swift
  Staccato-iOS/Staccato-iOS/Util/Manager/HomeModalManager.swift
  Staccato-iOS/Staccato-iOS/Util/Theme/StaccatoFont.swift
Labels: bug

#116 [Fix/#115] 스타카토 삭제시 리스트에 반영 안되는 오류 해결
  Staccato-iOS/Staccato-iOS/Presentation/View/Staccato/StaccatoDetailView.swift
  Staccato-iOS/Staccato-iOS/Presentation/ViewModel/Staccato/StaccatoDetailViewModel.swift
Labels: fix

#122 [Refactor/#119] 모달 크기 조정에 따른 GoogleMaps 움직임 리팩토링 (scrollBy 메소드 사용하는 방향으로)
  Staccato-iOS/Staccato-iOS.xcodeproj/project.pbxproj
  Staccato-iOS/Staccato-iOS/Presentation/View/Home/GMSMapViewRepresentable.swift
  Staccato-iOS/Staccato-iOS/Presentation/View/Home/HomeView.swift
  Staccato-iOS/Staccato-iOS/Util/Manager/HomeModalManager.swift
Labels: refactor

#126 [Feat/#125] 2.0 카테고리 목록, 카테고리 상세 조회 API(v3) 연결 및 UI 바인딩
  Staccato-iOS/Staccato-iOS/Model/Category/CategoryColorType.swift
  Staccato-iOS/Staccato-iOS/Model/Category/CategoryDetailModel.swift
  Staccato-iOS/Staccato-iOS/Model/Category/CategoryModel.swift
  Staccato-iOS/Staccato-iOS/Presentation/Components/StaccatoDatePicker/StaccatoDatePicker.swift
  Staccato-iOS/Staccato-iOS/Presentation/View/Category/CategoryEditorView.swift
  Staccato-iOS/Staccato-iOS/Presentation/View/Category/CategoryListCell.swift
  Staccato-iOS/Staccato-iOS/Presentation/View/Category/StaccatoCollectionCell.swift
  Staccato-iOS/Staccato-iOS/Resources/Assets.xcassets/Color/Marker/marker_indigo.colorset/Contents.json
  Staccato-iOS/Staccato-iOS/Resources/Assets.xcassets/Color/Marker/marker_indigo_light.colorset/Contents.json
  Staccato-iOS/Staccato-iOS/Resources/Assets.xcassets/Color/MarkerText/marker_txt_indigo_light.colorset/Contents.json
  Staccato-iOS/Staccato-iOS/Resources/Assets.xcassets/Image/markers/marker-indigo-light.imageset/Contents.json
  Staccato-iOS/Staccato-iOS/Resources/Assets.xcassets/Image/markers/marker-indigo-light.imageset/marker-staccato-blue-light.png
  Staccato-iOS/Staccato-iOS/Resources/Assets.xcassets/Image/markers/marker-indigo.imageset/Contents.json
  Staccato-iOS/Staccato-iOS/Resources/Assets.xcassets/Image/markers/marker-indigo.imageset/marker-staccato-blue.png
  Staccato-iOS/Staccato-iOS/Service/Category/CategoryEndpoint.swift
  Staccato-iOS/Staccato-iOS/Service/Category/DTO/GetCategoryDetailResponse.swift
  Staccato-iOS/Staccato-iOS/Service/Category/DTO/GetCategoryListResponse.swift
  Staccato-iOS/Staccato-iOS/Util/Extension/Ex+Date.swift
Labels: network

#130 [Feat/#94] 공유 카테고리 관련 레아이웃 생성
  Staccato-iOS/Staccato-iOS.xcodeproj/project.pbxproj
  Staccato-iOS/Staccato-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Staccato-iOS/Staccato-iOS/Model/Category/CategoryDetailModel.swift
  Staccato-iOS/Staccato-iOS/Model/Category/SearchedMemberModel.swift
  Staccato-iOS/Staccato-iOS/Presentation/Components/KeyboardDismissModifier.swift
  Staccato-iOS/Staccato-iOS/Presentation/View/Category/CategoryDetailMemberCell.swift
  Staccato-iOS/Staccato-iOS/Presentation/View/Category/CategoryDetailView.swift
  Staccato-iOS/Staccato-iOS/Presentation/View/Category/InviteMemberView.swift
  Staccato-iOS/Staccato-iOS/Presentation/ViewModel/Category/CategoryViewModel.swift
  Staccato-iOS/Staccato-iOS/Presentation/ViewModel/Category/InviteMemberViewModel.swift
  Staccato-iOS/Staccato-iOS/Resources/Assets.xcassets/Image/staccato_character_gray.imageset/Contents.json
  Staccato-iOS/Staccato-iOS/Resources/Assets.xcassets/Image/staccato_character_gray.imageset/staccato_chracter-1.png
  Staccato-iOS/Staccato-iOS/Resources/Assets.xcassets/Image/staccato_character_gray.imageset/staccato_chracter.png
  Staccato-iOS/Staccato-iOS/Resources/Assets.xcassets/Image/staccato_character_gray.imageset/staccato_chracter@3x.png
  Staccato-iOS/Staccato-iOS/Util/Extension/Ex+KFImage.swift
  Staccato-iOS/Staccato-iOS/Util/Extension/Ex+View.swift
  Staccato-iOS/Staccato-iOS/Util/Model/Member/Member.swift
  Staccato-iOS/Staccato-iOS/Util/Theme/StaccatoIcon.swift
Labels: feat
