Repository team-staccato/staccato-ios, pull requests merged in 2025-06, with the labels that each got.

#139 [Fix/#135] 카테고리, 스타카토, 마커 로직 및 UI 오류 해결
  Staccato-iOS/Staccato-iOS.xcodeproj/project.pbxproj
  Staccato-iOS/Staccato-iOS/Model/Staccato/StaccatoCoordinateModel.swift
  Staccato-iOS/Staccato-iOS/Presentation/View/Category/CategoryDetailView.swift
  Staccato-iOS/Staccato-iOS/Presentation/View/Category/CategoryEditorView.swift
  Staccato-iOS/Staccato-iOS/Presentation/View/Category/CategoryListView.swift
  Staccato-iOS/Staccato-iOS/Presentation/View/Home/HomeView.swift
  Staccato-iOS/Staccato-iOS/Presentation/View/Staccato/StaccatoEditorView.swift
  Staccato-iOS/Staccato-iOS/Presentation/ViewModel/Category/CategoryEditorViewModel.swift
  Staccato-iOS/Staccato-iOS/Presentation/ViewModel/Category/CategoryViewModel.swift
  Staccato-iOS/Staccato-iOS/Presentation/ViewModel/Home/HomeViewModel.swift
  Staccato-iOS/Staccato-iOS/Presentation/ViewModel/Staccato/StaccatoEditorViewModel.swift
  Staccato-iOS/Staccato-iOS/Service/Category/CategoryService.swift
  Staccato-iOS/Staccato-iOS/Service/Category/DTO/PostCategoryResponse.swift
Labels: fix

#142 [Fix/#141] Bottom Sheet 커스텀에서 기본 sheet로 수정
  Staccato-iOS/Staccato-iOS/App/AppDelegate.swift
  Staccato-iOS/Staccato-iOS/App/Staccato_iOSApp.swift
  Staccato-iOS/Staccato-iOS/Presentation/Components/StaccatoNavigationBar.swift
  Staccato-iOS/Staccato-iOS/Presentation/View/Category/CategoryDetailView.swift
  Staccato-iOS/Staccato-iOS/Presentation/View/Category/CategoryListView.swift
  Staccato-iOS/Staccato-iOS/Presentation/View/Home/GMSMapViewRepresentable.swift
  Staccato-iOS/Staccato-iOS/Presentation/View/Home/HomeView.swift
  Staccato-iOS/Staccato-iOS/Presentation/View/MyPage/MyPageView.swift
  Staccato-iOS/Staccato-iOS/Presentation/View/Staccato/StaccatoDetailView.swift
  Staccato-iOS/Staccato-iOS/Presentation/View/Staccato/StaccatoEditorView.swift
  Staccato-iOS/Staccato-iOS/Presentation/ViewModel/Staccato/StaccatoDetailViewModel.swift
  Staccato-iOS/Staccato-iOS/Util/Manager/BottomSheetDetentManager.swift
  Staccato-iOS/Staccato-iOS/Util/Manager/HomeModalManager.swift
  Staccato-iOS/Staccato-iOS/Util/Manager/STLocationManager.swift
Labels: fix, refactor, chore

#148 [Feat/#127] 스타카토 생성/수정 - 카테고리 목록 조회 API 연결 및 로직 수정
  Staccato-iOS/Staccato-iOS/Model/Category/CategoryCandidateModel.swift
  Staccato-iOS/Staccato-iOS/Model/Category/CategoryColorType.swift
  Staccato-iOS/Staccato-iOS/Model/Category/CategoryDetailModel.swift
  Staccato-iOS/Staccato-iOS/Model/Category/CategoryModel.swift
  Staccato-iOS/Staccato-iOS/Model/Staccato/StaccatoCoordinateModel.swift
  Staccato-iOS/Staccato-iOS/Model/Staccato/StaccatoDetailModel.swift
  Staccato-iOS/Staccato-iOS/Presentation/View/Category/CategoryDetailView.swift
  Staccato-iOS/Staccato-iOS/Presentation/View/Category/CategoryEditorView.swift
  Staccato-iOS/Staccato-iOS/Presentation/View/Category/CategoryListCell.swift
  Staccato-iOS/Staccato-iOS/Presentation/View/Home/GMSMapViewRepresentable.swift
  Staccato-iOS/Staccato-iOS/Presentation/View/Staccato/StaccatoEditorView.swift
  Staccato-iOS/Staccato-iOS/Presentation/ViewModel/Category/CategoryEditorViewModel.swift
  Staccato-iOS/Staccato-iOS/Presentation/ViewModel/Home/HomeViewModel.swift
  Staccato-iOS/Staccato-iOS/Presentation/ViewModel/Staccato/StaccatoEditorViewModel.swift
  Staccato-iOS/Staccato-iOS/Service/Category/CategoryEndpoint.swift
  Staccato-iOS/Staccato-iOS/Service/Category/CategoryService.swift
  Staccato-iOS/Staccato-iOS/Service/Category/DTO/GetCategoryCandidatesRequestQuery.swift
  Staccato-iOS/Staccato-iOS/Service/Category/DTO/GetCategoryCandidatesResponse.swift
  Staccato-iOS/Staccato-iOS/Service/Staccato/DTO/GetStaccatoDetailResponse.swift
  Staccato-iOS/Staccato-iOS/Service/Staccato/StaccatoEndpoint.swift
Labels: fix, network

#151 [Fix/#150] Google Map API 연속 호출 수정
  Staccato-iOS/Staccato-iOS/Presentation/View/Home/HomeView.swift
  Staccato-iOS/Staccato-iOS/Util/Manager/BottomSheetDetentManager.swift
Labels: fix

#138 [Feat/#134] 카테고리 초대 관리 기능 추가
  Staccato-iOS/Staccato-iOS.xcodeproj/project.pbxproj
  Staccato-iOS/Staccato-iOS.xcodeproj/xcuserdata/gyunni.xcuserdatad/xcschemes/xcschememanagement.plist
  Staccato-iOS/Staccato-iOS/Model/Invitation/InvitationModel.swift
  Staccato-iOS/Staccato-iOS/Presentation/View/Category/CategoryEditorView.swift
  Staccato-iOS/Staccato-iOS/Presentation/View/Home/HomeView.swift
  Staccato-iOS/Staccato-iOS/Presentation/View/MyPage/CategoryInvitationManager/CategoryInvitationManagerView.swift
  Staccato-iOS/Staccato-iOS/Presentation/View/MyPage/CategoryInvitationManager/ReceivedInvitationCell.swift
  Staccato-iOS/Staccato-iOS/Presentation/View/MyPage/CategoryInvitationManager/SentInvitationCell.swift
  Staccato-iOS/Staccato-iOS/Presentation/View/MyPage/MyPageView.swift
  Staccato-iOS/Staccato-iOS/Presentation/View/Staccato/StaccatoEditorView.swift
  Staccato-iOS/Staccato-iOS/Presentation/ViewModel/Invitation/CategoryInvitationManagerViewModel.swift
  Staccato-iOS/Staccato-iOS/Resources/Assets.xcassets/Color/staccato_red.colorset/Contents.json
  Staccato-iOS/Staccato-iOS/Service/Category/DTO/GetCategoriesCandidatesRequestQuery.swift
  Staccato-iOS/Staccato-iOS/Service/Category/DTO/GetCategoriesCandidatesResponse.swift
  Staccato-iOS/Staccato-iOS/Service/Invitation/DTO/GetReceivedInvitaionsResponse.swift
  Staccato-iOS/Staccato-iOS/Service/Invitation/DTO/GetSentInvitationsResponse.swift
  Staccato-iOS/Staccato-iOS/Service/Invitation/DTO/PostInvitationsRequest.swift
  Staccato-iOS/Staccato-iOS/Service/Invitation/DTO/PostInvitationsResponse.swift
  Staccato-iOS/Staccato-iOS/Service/Invitation/InvitationEndPoint.swift
  Staccato-iOS/Staccato-iOS/Service/Invitation/InvitationService.swift
  Staccato-iOS/Staccato-iOS/Service/Invite/InvitationEndPoint.swift
  Staccato-iOS/Staccato-iOS/Service/Invite/InvitationService.swift
  Staccato-iOS/Staccato-iOS/Service/Notication/DTO/GetgetHasNotificationResponse.swift
  Staccato-iOS/Staccato-iOS/Service/Notication/NotificationEndPoint.swift
  Staccato-iOS/Staccato-iOS/Service/Notication/NotificationService.swift
  Staccato-iOS/Staccato-iOS/Util/Manager/STNotificationManager.swift
  Staccato-iOS/Staccato-iOS/Util/Network/STService.swift
Labels: feat

#155 [Hotfix/#152] 릴리즈 준비 및 에러 긴급 대응
  Staccato-iOS/Staccato-iOS.xcodeproj/project.pbxproj
  Staccato-iOS/Staccato-iOS.xcodeproj/xcshareddata/xcschemes/Staccato-iOS.xcscheme
  Staccato-iOS/Staccato-iOS/App/Staccato_iOSApp.swift
  Staccato-iOS/Staccato-iOS/Presentation/Components/StaccatoAlertView.swift
  Staccato-iOS/Staccato-iOS/Presentation/View/Category/CategoryDetailView.swift
  Staccato-iOS/Staccato-iOS/Presentation/View/Category/CategoryEditorView.swift
  Staccato-iOS/Staccato-iOS/Presentation/View/Category/CategoryListView.swift
  Staccato-iOS/Staccato-iOS/Presentation/View/Home/HomeView.swift
  Staccato-iOS/Staccato-iOS/Presentation/View/MyPage/CategoryInvitationManager/CategoryInvitationManagerView.swift
  Staccato-iOS/Staccato-iOS/Presentation/View/MyPage/MyPageView.swift
  Staccato-iOS/Staccato-iOS/Presentation/View/SignIn/RecoverAccountView.swift
  Staccato-iOS/Staccato-iOS/Presentation/View/SignIn/SignInView.swift
  Staccato-iOS/Staccato-iOS/Presentation/View/Staccato/CameraView.swift
  Staccato-iOS/Staccato-iOS/Presentation/View/Staccato/StaccatoDetailView.swift
  Staccato-iOS/Staccato-iOS/Presentation/View/Staccato/StaccatoEditorView.swift
  Staccato-iOS/Staccato-iOS/Presentation/ViewModel/Staccato/StaccatoDetailViewModel.swift
  Staccato-iOS/Staccato-iOS/Util/Manager/BottomSheetDetentManager.swift
  Staccato-iOS/Staccato-iOS/Util/NavigationState/NavigationState.swift
Labels: hotfix, 🚀 release

#157 [Feat/#154] 공동 카테고리 나가기 기능 구현
  Staccato-iOS/Staccato-iOS/Presentation/View/Category/CategoryDetailView.swift
  Staccato-iOS/Staccato-iOS/Presentation/ViewModel/Category/CategoryViewModel.swift
  Staccato-iOS/Staccato-iOS/Service/Category/CategoryEndpoint.swift
  Staccato-iOS/Staccato-iOS/Service/Category/CategoryService.swift
  Staccato-iOS/Staccato-iOS/Util/Manager/StaccatoAlertManager.swift
Labels: feat

#159 [Chore/#158] 리드미 꾸미기 ~
  README.md
Labels: docs, chore

#167 [Feat/#166] 2.0.0 기능 QA 적용
  Staccato-iOS/Staccato-iOS/Presentation/View/Category/CategoryEditorView.swift
  Staccato-iOS/Staccato-iOS/Presentation/View/Category/InvitationMemberView.swift
  Staccato-iOS/Staccato-iOS/Presentation/View/MyPage/MyPageView.swift
  Staccato-iOS/Staccato-iOS/Presentation/View/Staccato/CameraView.swift
  Staccato-iOS/Staccato-iOS/Presentation/View/Staccato/StaccatoEditorView.swift
  Staccato-iOS/Staccato-iOS/Presentation/ViewModel/Category/CategoryEditorViewModel.swift
  Staccato-iOS/Staccato-iOS/Presentation/ViewModel/Category/InvitationMemberViewModel.swift
  Staccato-iOS/Staccato-iOS/Presentation/ViewModel/Staccato/StaccatoEditorViewModel.swift
Labels: feat, fix

#169 [Fix/#168] 디자인 QA 반영
  Staccato-iOS/Staccato-iOS/Model/Staccato/FeelingType.swift
  Staccato-iOS/Staccato-iOS/Presentation/View/Category/CategoryDetailView.swift
  Staccato-iOS/Staccato-iOS/Presentation/View/Category/CategoryEditorView.swift
  Staccato-iOS/Staccato-iOS/Presentation/View/Category/CategoryListCell.swift
  Staccato-iOS/Staccato-iOS/Presentation/View/SignIn/SignInView.swift
  Staccato-iOS/Staccato-iOS/Presentation/View/Staccato/StaccatoDetailView.swift
  Staccato-iOS/Staccato-iOS/Resources/Assets.xcassets/Image/feelings/feeling_angry_gray.imageset/Contents.json
  Staccato-iOS/Staccato-iOS/Resources/Assets.xcassets/Image/feelings/feeling_angry_gray.imageset/feeling_angry_gray.png
  Staccato-iOS/Staccato-iOS/Resources/Assets.xcassets/Image/feelings/feeling_angry_gray.imageset/feeling_angry_gray@2x.png
  Staccato-iOS/Staccato-iOS/Resources/Assets.xcassets/Image/feelings/feeling_angry_gray.imageset/feeling_angry_gray@3x.png
  Staccato-iOS/Staccato-iOS/Resources/Assets.xcassets/Image/feelings/feeling_excited_gray.imageset/Contents.json
  Staccato-iOS/Staccato-iOS/Resources/Assets.xcassets/Image/feelings/feeling_excited_gray.imageset/feeling_excited_gray.png
  Staccato-iOS/Staccato-iOS/Resources/Assets.xcassets/Image/feelings/feeling_excited_gray.imageset/feeling_excited_gray@2x.png
  Staccato-iOS/Staccato-iOS/Resources/Assets.xcassets/Image/feelings/feeling_excited_gray.imageset/feeling_excited_gray@3x.png
  Staccato-iOS/Staccato-iOS/Resources/Assets.xcassets/Image/feelings/feeling_happy_gray.imageset/Contents.json
  Staccato-iOS/Staccato-iOS/Resources/Assets.xcassets/Image/feelings/feeling_happy_gray.imageset/feeling_happy_gray.png
  Staccato-iOS/Staccato-iOS/Resources/Assets.xcassets/Image/feelings/feeling_happy_gray.imageset/feeling_happy_gray@2x.png
  Staccato-iOS/Staccato-iOS/Resources/Assets.xcassets/Image/feelings/feeling_happy_gray.imageset/feeling_happy_gray@3x.png
  Staccato-iOS/Staccato-iOS/Resources/Assets.xcassets/Image/feelings/feeling_sad_gray.imageset/Contents.json
  Staccato-iOS/Staccato-iOS/Resources/Assets.xcassets/Image/feelings/feeling_sad_gray.imageset/feeling_sad_gray.png
  Staccato-iOS/Staccato-iOS/Resources/Assets.xcassets/Image/feelings/feeling_sad_gray.imageset/feeling_sad_gray@2x.png
  Staccato-iOS/Staccato-iOS/Resources/Assets.xcassets/Image/feelings/feeling_sad_gray.imageset/feeling_sad_gray@3x.png
  Staccato-iOS/Staccato-iOS/Resources/Assets.xcassets/Image/feelings/feeling_scared_gray.imageset/Contents.json
  Staccato-iOS/Staccato-iOS/Resources/Assets.xcassets/Image/feelings/feeling_scared_gray.imageset/feeling_scared_gray.png
  Staccato-iOS/Staccato-iOS/Resources/Assets.xcassets/Image/feelings/feeling_scared_gray.imageset/feeling_scared_gray@2x.png
  Staccato-iOS/Staccato-iOS/Resources/Assets.xcassets/Image/feelings/feeling_scared_gray.imageset/feeling_scared_gray@3x.png
  Staccato-iOS/Staccato-iOS/Resources/Assets.xcassets/Image/staccato_launch_screen_logo.imageset/Contents.json
  Staccato-iOS/Staccato-iOS/Resources/Assets.xcassets/Image/staccato_launch_screen_logo.imageset/LaunchScreenLogo.png
  Staccato-iOS/Staccato-iOS/Resources/Assets.xcassets/Image/staccato_login_logo.imageset/staccato_login_logo.png
  Staccato-iOS/Staccato-iOS/Resources/Assets.xcassets/Image/staccato_login_logo.imageset/staccato_login_logo@2x.png
  Staccato-iOS/Staccato-iOS/Resources/Assets.xcassets/Image/staccato_login_logo.imageset/staccato_login_logo@3x.png
  Staccato-iOS/Staccato-iOS/Resources/Assets.xcassets/Image/staccato_logo.imageset/Contents.json
  Staccato-iOS/Staccato-iOS/Resources/Assets.xcassets/Image/staccato_logo.imageset/staccato_logo.png
  Staccato-iOS/Staccato-iOS/Resources/Assets.xcassets/Image/staccato_logo.imageset/staccato_logo@2x.png
  Staccato-iOS/Staccato-iOS/Resources/Assets.xcassets/Image/staccato_logo.imageset/staccato_logo@3x.png
  Staccato-iOS/Staccato-iOS/Support/LaunchScreen.storyboard
  Staccato-iOS/Staccato-iOS/Util/Theme/StaccatoIcon.swift
Labels: fix

#181 [Fix/#180] 코멘트 Long Press 제스처 UI 수정
  Staccato-iOS/Staccato-iOS/Presentation/Staccato/View/StaccatoDetailView.swift
  Staccato-iOS/Staccato-iOS/Presentation/Staccato/ViewModel/StaccatoDetailViewModel.swift
Labels: 🛠️ Fix
