Repository team-staccato/staccato-ios, pull requests merged in 2025-04, with the labels that each got.

#61 [Feat/#60] 유저아이디 파싱, commentService - View 연결
  Staccato-iOS/Staccato-iOS/App/Staccato_iOSApp.swift
  Staccato-iOS/Staccato-iOS/Model/Staccato/CommentModel.swift
  Staccato-iOS/Staccato-iOS/Model/Staccato/StaccatoDetailModel.swift
  Staccato-iOS/Staccato-iOS/Presentation/View/CategoryList/CategoryListView.swift
  Staccato-iOS/Staccato-iOS/Presentation/View/Home/GMSMapViewRepresentable.swift
  Staccato-iOS/Staccato-iOS/Presentation/View/StaccatoDetail/StaccatoDetailView.swift
  Staccato-iOS/Staccato-iOS/Presentation/ViewModel/Home/HomeViewModel.swift
  Staccato-iOS/Staccato-iOS/Presentation/ViewModel/StaccatoDetail/StaccatoDetailViewModel.swift
  Staccato-iOS/Staccato-iOS/Util/Manager/AuthTokenManager.swift
  Staccato-iOS/Staccato-iOS/Util/Theme/StaccatoIcon.swift
Labels: feat, 🥑 유림

#62 [Feat/#34] 사진 업로드 기능 구현
  Staccato-iOS/Staccato-iOS.xcodeproj/project.pbxproj
  Staccato-iOS/Staccato-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Staccato-iOS/Staccato-iOS/Presentation/Components/CameraView.swift
  Staccato-iOS/Staccato-iOS/Presentation/View/Staccato/StaccatoCreateView.swift
  Staccato-iOS/Staccato-iOS/Resources/Lottie/UploadImage.json
Labels: feat

#67 [Refactor/#64] Navigation 로직 개선
  Staccato-iOS/Staccato-iOS/App/Staccato_iOSApp.swift
  Staccato-iOS/Staccato-iOS/Presentation/Components/StaccatoNavigationBar.swift
  Staccato-iOS/Staccato-iOS/Presentation/View/CategoryList/CategoryListView.swift
  Staccato-iOS/Staccato-iOS/Presentation/View/Home/GMSMapViewRepresentable.swift
  Staccato-iOS/Staccato-iOS/Presentation/View/Home/HomeView.swift
  Staccato-iOS/Staccato-iOS/Presentation/View/MyPage/MyPageView.swift
  Staccato-iOS/Staccato-iOS/Presentation/ViewModel/Home/HomeViewModel.swift
  Staccato-iOS/Staccato-iOS/Util/NavigationState/NavigationState.swift
Labels: refactor, 🥑 유림

#68 [Feat/#65] 커스텀 Alert 컴포넌트 구현
  Staccato-iOS/Staccato-iOS/App/Staccato_iOSApp.swift
  Staccato-iOS/Staccato-iOS/Presentation/Components/StaccatoAlertView.swift
  Staccato-iOS/Staccato-iOS/Presentation/Components/StaccatoButtonStyle.swift
  Staccato-iOS/Staccato-iOS/Presentation/Components/TransparentViewRepresentable.swift
  Staccato-iOS/Staccato-iOS/Presentation/View/Category/CategoryDetailView.swift
  Staccato-iOS/Staccato-iOS/Presentation/View/Home/HomeView.swift
  Staccato-iOS/Staccato-iOS/Presentation/View/SignIn/SignInView.swift
  Staccato-iOS/Staccato-iOS/Util/Extension/Ex+ButtonStyle.swift
  Staccato-iOS/Staccato-iOS/Util/Manager/StaccatoAlertManager.swift
Labels: feat, 🥑 유림

#66 [Feat/#63] 카테고리 - API 연결(GET, DEL), 화면 전환(셀, 추가, 삭제)
  Staccato-iOS/Staccato-iOS/Model/Category/CategoryDetailModel.swift
  Staccato-iOS/Staccato-iOS/Model/Category/CategoryModel.swift
  Staccato-iOS/Staccato-iOS/Presentation/View/Category/CategoryDetailView.swift
  Staccato-iOS/Staccato-iOS/Presentation/View/Category/CategoryListCell.swift
  Staccato-iOS/Staccato-iOS/Presentation/View/Category/CategoryListSortFilterView.swift
  Staccato-iOS/Staccato-iOS/Presentation/View/Category/CategoryListView.swift
  Staccato-iOS/Staccato-iOS/Presentation/View/Category/StaccatoCollectionCell.swift
  Staccato-iOS/Staccato-iOS/Presentation/ViewModel/CategoryEditor/CategoryEditorViewModel.swift
  Staccato-iOS/Staccato-iOS/Presentation/ViewModel/CategoryList/CategoryDetailViewModel.swift
  Staccato-iOS/Staccato-iOS/Presentation/ViewModel/CategoryList/CategoryListViewModel.swift
  Staccato-iOS/Staccato-iOS/Service/Category/CategoryEndpoint.swift
  Staccato-iOS/Staccato-iOS/Service/Category/CategoryService.swift
  Staccato-iOS/Staccato-iOS/Service/Category/DTO/GetCategoryDetailResponse.swift
  Staccato-iOS/Staccato-iOS/Util/Model/Memory/MemoriesResponse.swift
  Staccato-iOS/Staccato-iOS/Util/Model/Memory/MemoryCreationResponse.swift
  Staccato-iOS/Staccato-iOS/Util/Model/Memory/MemoryMoment.swift
  Staccato-iOS/Staccato-iOS/Util/Model/Memory/MemoryRequest.swift
  Staccato-iOS/Staccato-iOS/Util/Model/Memory/MemoryResponse.swift
  Staccato-iOS/Staccato-iOS/Util/NavigationState/NavigationState.swift
  Staccato-iOS/Staccato-iOS/Util/Network/STService.swift
Labels: feat, network, 🥑 유림

#71 Feat/#55 network mypage
  Staccato-iOS/Staccato-iOS/Presentation/View/Category/CategoryEditorView.swift
  Staccato-iOS/Staccato-iOS/Presentation/View/MyPage/MyPageView.swift
  Staccato-iOS/Staccato-iOS/Presentation/ViewModel/CategoryEditor/CategoryEditorViewModel.swift
  Staccato-iOS/Staccato-iOS/Presentation/ViewModel/MyPage/MyPageViewModel.swift
  Staccato-iOS/Staccato-iOS/Service/Category/CategoryEndpoint.swift
  Staccato-iOS/Staccato-iOS/Service/MyPage/DTO/ImageResponse.swift
  Staccato-iOS/Staccato-iOS/Service/MyPage/DTO/PostProfileImageRequest.swift
  Staccato-iOS/Staccato-iOS/Service/MyPage/DTO/PostProfileImageResponse.swift
  Staccato-iOS/Staccato-iOS/Service/MyPage/MyPageEndPoint.swift
  Staccato-iOS/Staccato-iOS/Service/MyPage/MyPageService.swift
  Staccato-iOS/Staccato-iOS/Util/Network/NetworkService.swift
Labels: feat, network

#84 이미지 업로드 빌드 오류 수정, 자동로그인
  Staccato-iOS/Staccato-iOS/Presentation/View/SignIn/SignInView.swift
  Staccato-iOS/Staccato-iOS/Presentation/View/Staccato/StaccatoCreateView.swift
  Staccato-iOS/Staccato-iOS/Presentation/ViewModel/CategoryEditor/CategoryEditorViewModel.swift
  Staccato-iOS/Staccato-iOS/Presentation/ViewModel/MyPage/MyPageViewModel.swift
  Staccato-iOS/Staccato-iOS/Presentation/ViewModel/SignIn/SignInViewModel.swift
  Staccato-iOS/Staccato-iOS/Service/Category/CategoryEndpoint.swift
  Staccato-iOS/Staccato-iOS/Service/Image/DTO/ImageEndPoint.swift
  Staccato-iOS/Staccato-iOS/Service/Image/DTO/ImageResponse.swift
  Staccato-iOS/Staccato-iOS/Service/Image/DTO/ImageService.swift
  Staccato-iOS/Staccato-iOS/Service/Image/DTO/PostImageRequest.swift
  Staccato-iOS/Staccato-iOS/Service/MyPage/DTO/PostProfileImageRequest.swift
  Staccato-iOS/Staccato-iOS/Service/MyPage/DTO/PostProfileImageResponse.swift
  Staccato-iOS/Staccato-iOS/Service/MyPage/MyPageEndPoint.swift
  Staccato-iOS/Staccato-iOS/Service/MyPage/MyPageService.swift
  Staccato-iOS/Staccato-iOS/Util/Model/MyPage/ProfileImageResponse.swift
  Staccato-iOS/Staccato-iOS/Util/Network/STService.swift
Labels: feat, hotfix

#80 [Feat/#79] (스타카토 생성) GooglePlaces SDK로 장소 검색 기능 구현, 역지오코딩 구현, LocationManager 통합
  Staccato-iOS/Staccato-iOS/Model/Staccato/StaccatoPlaceModel.swift
  Staccato-iOS/Staccato-iOS/Presentation/Components/StaccatoButtonStyle.swift
  Staccato-iOS/Staccato-iOS/Presentation/View/Category/CategoryListView.swift
  Staccato-iOS/Staccato-iOS/Presentation/View/Home/GMSMapViewRepresentable.swift
  Staccato-iOS/Staccato-iOS/Presentation/View/Home/HomeView.swift
  Staccato-iOS/Staccato-iOS/Presentation/View/Staccato/GMSPlaceSearchViewController.swift
  Staccato-iOS/Staccato-iOS/Presentation/View/Staccato/LocationManager.swift
  Staccato-iOS/Staccato-iOS/Presentation/View/Staccato/StaccatoCreateView.swift
  Staccato-iOS/Staccato-iOS/Presentation/ViewModel/Home/HomeViewModel.swift
  Staccato-iOS/Staccato-iOS/Util/Extension/Ex+ButtonStyle.swift
  Staccato-iOS/Staccato-iOS/Util/Manager/LocationAuthorizationManager.swift
  Staccato-iOS/Staccato-iOS/Util/Manager/STLocationManager.swift
Labels: feat, 🥑 유림

#83 [Fix/#69] GMS API가 불필요하게 많이 호출되는 문제 해결 (+ 기타 지도 기능 구현 및 리팩토링)
  Staccato-iOS/Staccato-iOS/Model/Staccato/StaccatoCoordinateModel.swift
  Staccato-iOS/Staccato-iOS/Presentation/View/Home/GMSMapViewRepresentable.swift
  Staccato-iOS/Staccato-iOS/Presentation/View/Home/HomeView.swift
  Staccato-iOS/Staccato-iOS/Presentation/ViewModel/Home/HomeViewModel.swift
Labels: feat, fix, 🥑 유림

#76 [Feat/#73] Launch Screen 구현
  Staccato-iOS/Staccato-iOS.xcodeproj/project.pbxproj
  Staccato-iOS/Staccato-iOS/Resources/Assets.xcassets/Image/LaunchScreenLogo.imageset/Contents.json
  Staccato-iOS/Staccato-iOS/Resources/Assets.xcassets/Image/LaunchScreenLogo.imageset/LaunchScreenLogo.png
  Staccato-iOS/Staccato-iOS/Support/Info.plist
  Staccato-iOS/Staccato-iOS/Support/LaunchScreen.storyboard
Labels: feat
